Replace Apollo 11 flightplan with one that has Revision A changes
dseagrav/NASSP pull request #1002
Opened 2023-06-01 00:59 UTC by maxq519

2023-06-02 15:10 UTC, rcflyinghokie approved these changes, later dismissed
Looks good, just increase the install size of course since its the HSK flight plan.

2023-06-02 18:21 UTC, maxq519 commented
I compressed it as much as I could without loosing too much quality.
I can compress it more and see how the quality is if you want.

2023-06-03 20:35 UTC, indy91 requested changes
I'm not really sure what this does. The HSK flight plan has some, but not all the revision A changes, so we consider it the superior version? What is this change in page 1-10, changing the launch time on July 16 to 1209 EDT. That is wrong and not in the HSK version. It's the July 21 launch date that was in error, like the change document says: https://de.scribd.com/doc/46181272/Apollo-11-Final-Flight-Plan-Revision-A

Haven't checked for any more errors yet.

2023-06-12 20:37 UTC, indy91 approved these changes

2023-06-12 20:37 UTC, merged