Add IMU and Gyro Drift Rates and Accelerometer Biases
dseagrav/NASSP pull request #1030
Opened 2023-07-17 01:52 UTC by n7275

This is very much WIP. Adding so it doesn't get lost.

2023-08-06 20:52 UTC, n7275 commented
IMU drift compensation from the CMC, showing NBDX,Y,Z ADIAX,Y,Z and ADSRAX,Y,Z combined. CMC is compensation for NBD before, and after an 1800 ft/sec SPS burn, and compensating for all three during the burn.
![image](https://github.com/orbiternassp/NASSP/assets/100335/0179f606-ff75-4ac7-877a-3fc391793d9b)


All three axes have been tested separately to confirm sign and handedness in the CM/CMC.

on to the LM...

2024-03-09 21:27 UTC, n7275 commented
Testing State vector for Apollo 11 Launch

![image](https://github.com/orbiternassp/NASSP/assets/100335/8ca4c322-72ac-485e-a538-a1e902c8a1c0)
![image](https://github.com/orbiternassp/NASSP/assets/100335/244bb3fc-238f-41df-a5c9-2672a3bebafd)

2024-06-05 20:43 UTC, rcflyinghokie commented
#1247 can you add this to your branch to prevent merge conflicts with OO?

2024-06-05 21:35 UTC, rcflyinghokie requested changes, later dismissed
imu.cpp the "scanf" need to be "sscanf"

2024-06-08 14:35 UTC, rcflyinghokie commented
just need to resolve the merge conflict on the Apollo 10 LM pads that you got from pulling the main branch

2024-06-08 14:59 UTC, n7275 commented
> just need to resolve the merge conflict on the Apollo 10 LM pads that you got from pulling the main branch

Should be fixed now.

2024-06-16 08:39 UTC, ThatRedMelon submitted a review, later dismissed
Flown whole Apollo 11 flight without issues

2024-06-17 18:47 UTC, indy91 requested changes

2024-06-17 18:47 UTC, indy91 commented on Scenarios/Project Apollo - NASSP/Apollo - Mission Scenarios/Apollo 10/Apollo 10 - 10 - Before Undocking T+98h15min.scn
Scenario edit error, the two added sections are together in the LGC memory and not separately in CMC and LGC.

2024-06-17 18:47 UTC, indy91 commented on Scenarios/Project Apollo - NASSP/Apollo 9 - Launch.scn
> +  LMPAD 1454 01454
Value should be 1744 and not 1454, same in all Apollo 9 scenarios.

2024-06-17 18:47 UTC, indy91 commented on Scenarios/Project Apollo - NASSP/Apollo - Mission Scenarios/Apollo 10/Apollo 10 - 12 - Before Phasing TIG-6min.scn
LGC padloads got added to both CMC and LGC here.

2024-06-17 18:47 UTC, indy91 commented on Missions/ProjectApollo/Apollo 10.cfg
I believe there is a sign error in the CMPIPABIASZ value. Here is an extract of the Apollo 10 CMC padload:

![image](https://github.com/orbiternassp/NASSP/assets/13571607/16153b3b-78a7-4149-936c-605e9f054874)

-0.05 gives the correct padload.

CMADSRAY also differs from the document, but it's not just a simple sign error.

2024-06-17 18:47 UTC, indy91 commented on Missions/ProjectApollo/Apollo 10.cfg
> +LMNBDZ=1.2
Should be -1.2 and not 1.2, see flown padload.

2024-06-18 02:16 UTC, n7275 commented on Missions/ProjectApollo/Apollo 10.cfg
Looks like I accidentally copied in the -1.3 from CMNBDY into CMADSRAY, correct value should be around 3.0

2024-06-18 17:44 UTC, indy91 requested changes

2024-06-18 17:44 UTC, indy91 commented on Scenarios/Project Apollo - NASSP/Apollo - Mission Scenarios/Apollo 9/Apollo 9 - 33 - Before Entry Interface.scn
The padload for the CMC got copied to both CMC and LGC in this scenario. Not really significant because the LM is long dead by this point, but maybe should still be removed.

2024-06-18 17:44 UTC, indy91 commented on Missions/ProjectApollo/Apollo 10.cfg
> +LMNBDZ=1.2
You changed CMNBDZ from 1.2 to -1.2, when you should have changed LMNDBZ from 1.2 to -1.2. CMNBDZ should be positive, LMNDBZ negative. Sadly they have the same value, just different signs, for maximum confusion.

2024-06-18 17:44 UTC, indy91 commented on Scenarios/Project Apollo - NASSP/Apollo - Mission Scenarios/Apollo 11/Apollo 11 - 17 - Before Lunar Liftoff T+124h20min.scn
This scenario doesn't have the LGC padloads.

2024-06-18 17:44 UTC, indy91 commented on Missions/ProjectApollo/Apollo 11.cfg
Where are these LM biases coming from? They don't agree with the flown padload, neither the biases nor the bias compensation.

2024-06-18 17:44 UTC, indy91 commented on Scenarios/Project Apollo - NASSP/Apollo 12 - Launch.scn
The CMC padload here reverses the changes that were done for switching from Comanche 55 to 67.

2024-06-18 17:44 UTC, indy91 commented on Missions/ProjectApollo/Apollo 12.cfg
CSM values here are for the actual behavior on the mission? CMPIPABIASX is zero but it's not zero in the padload.

2024-06-20 01:10 UTC, n7275 commented on Missions/ProjectApollo/Apollo 11.cfg
Ahh, whoops. it looks like I used this one by mistake: https://www.ibiblio.org/apollo/Documents/Luminary99PadLoads.pdf

I will update to the correct ones

2024-07-01 15:30 UTC, indy91 commented on Scenarios/Project Apollo - NASSP/Apollo 9 - Launch.scn
> +  LMPAD 1454 01454
Two Apollo 9 scenarios still have this typo for the LGC with address 1454 also having value 1454, when it should be value3 1744.

2024-07-01 15:37 UTC, indy91 commented on Scenarios/Project Apollo - NASSP/Apollo - Mission Scenarios/Apollo 10/Apollo 10 - 12 - Before Phasing TIG-6min.scn
> +  EMEM1470 77745
Copy and paste mistake, second EMEM1470 should be removed (it comes from the LGC erasable).

2024-07-01 15:53 UTC, indy91 requested changes

2024-07-01 15:53 UTC, indy91 commented on Scenarios/Project Apollo - NASSP/Apollo - Mission Scenarios/Apollo 10/Apollo 10 - 13 - Before Insertion TIG-11min.scn
> +  EMEM 1467 00064
This won't load right with the empty space.

2024-07-01 15:53 UTC, indy91 commented on Scenarios/Project Apollo - NASSP/Apollo 10 - Launch.scn
None of the Apollo 10 mission scenarios have the correct sign for the LM NBDZ (address 1462). It got changed to a negative value in the mission file, but not in the padload.

2024-07-05 04:27 UTC, n7275 commented on Scenarios/Project Apollo - NASSP/Apollo 12 - Launch.scn
I think this may have been the result of a bad merge-conflict resolution on my part.

2024-07-08 19:53 UTC, indy91 approved these changes

2024-07-08 19:54 UTC, indy91 commented
All issues are resolved

2024-07-08 20:42 UTC, merged