Add Skylab Vessel
dseagrav/NASSP pull request #1054
Opened 2023-08-20 18:41 UTC by n7275

2023-08-22 22:02 UTC, maxq519 requested changes
Could we have the included "Skylab 2 - Launch" scenario reference this vessel instead of the external addon?

2023-08-23 03:37 UTC, n7275 commented
> Could we have the included "Skylab 2 - Launch" scenario reference this vessel instead of the external addon?

I don't see why not, the only downside is that our Skylab has no thrusters yet. It picks up any attitude rate before rendezvous that might make things hard. I can add some simple ones soon though.

2023-08-23 15:11 UTC, indy91 approved these changes

2023-08-23 16:16 UTC, maxq519 approved these changes

2023-08-23 16:53 UTC, merged