Update appveyor.yml to package XRSound configuration separately
dseagrav/NASSP pull request #1199
Opened 2024-03-10 22:51 UTC by dseagrav

This is so people can change xrsound's configuration but still use zipfiles for updates

2024-03-10 23:39 UTC, CaptainSwag101 approved these changes
Looks good to me.

2024-03-11 13:53 UTC, CaptainSwag101 requested changes
Could the new zip file be called "XRSound-config" perhaps instead of just "XRSound"? A user had some confusion and thought this was XRSound itself when it's just the default configs.

2024-03-12 18:49 UTC, indy91 approved these changes

2024-03-12 18:50 UTC, CaptainSwag101 approved these changes
Everything looks good now, thanks!

2024-03-12 18:50 UTC, merged