Virtual cockpit
dseagrav/NASSP pull request #1235
Opened 2024-05-23 03:48 UTC by Jordan-64

New Ordeal knob for CMVC and LMVC.
New frame for LM CW lights and new texture.
New EMS Lift Vector indicators.
Add LM VC Tapemeter Lighting.
All single lights CW, DSKY etc are now independent lit.

2024-10-30 16:48 UTC, rcflyinghokie commented
Is there any reason this still needs to be draft?

2024-10-30 19:58 UTC, Jordan-64 commented
> Is there any reason this still needs to be draft?

I wanted to finish the cm meters on panel 2 and 3 first. 
Actually, I'm waiting until someone wants to merge it. Is it stable enough? If so, then I can finish the meters later.

2024-12-19 15:47 UTC, rcflyinghokie approved these changes, later dismissed
Testing this works very well, mathematical models provide the best fit for the gauges right now until we have a better ides of how they actually handled the non linear scaling.

2024-12-19 23:52 UTC, TINYBOB1 approved these changes, later dismissed
Works as intended.  animations all check out, nothing unexpected

2024-12-27 15:48 UTC, rcflyinghokie requested changes
bmp files for 2D CM cockpit will not load on this revision

2024-12-27 18:06 UTC, TINYBOB1 commented
In what way does it not load?  I'm not available to test right now, just curious what the symptoms are.

2025-01-04 09:22 UTC, Jordan-64 commented
> bmp files for 2D CM cockpit will not load on this revision

2025-01-04 09:42 UTC, Jordan-64 reviewed
bmp's not loading fixed.

2025-01-04 18:12 UTC, rcflyinghokie commented
> In what way does it not load? I'm not available to test right now, just curious what the symptoms are.

compression

2025-01-04 18:13 UTC, rcflyinghokie submitted a review, later dismissed

2025-01-06 18:52 UTC, jalexb88 commented
Once I land my Apollo 12 LM on the moon I will make my review...so far so good up to LM activation.

2025-01-07 06:30 UTC, jalexb88 submitted a review, later dismissed
Tested from launch to lunar landing on Apollo 12 with O2024. No major issues.

2025-01-07 14:14 UTC, rcflyinghokie commented
I will check the other gauges this week and then relist my approval

2025-01-21 21:13 UTC, rcflyinghokie submitted a review, later dismissed

2025-01-22 04:53 UTC, CaptainSwag101 commented
I will try to fly my next mission using this branch, and see how everything works. I might see about creating a custom font for the cockpit EL displays like the LM numeric displays and the CM mission timers, since we now know those were likely both a different color and used a different font.

2025-02-12 18:57 UTC, CaptainSwag101 approved these changes, later dismissed
Everything looks fantastic!

2025-02-12 19:04 UTC, maxq519 submitted a review, later dismissed
Everything looks amazing!

2025-02-12 19:07 UTC, ThatRedMelon submitted a review, later dismissed
Looks gorgeous!

2025-02-12 20:25 UTC, indy91 requested changes

2025-02-12 20:25 UTC, indy91 commented on Orbitersdk/samples/ProjectApollo/src_sys/missiontimer.cpp
As discussed on Discord, this file needs the build warnings fixed and the tuning fork code added.

2025-02-12 20:26 UTC, CaptainSwag101 commented on Orbitersdk/samples/ProjectApollo/src_sys/missiontimer.cpp
PR outstanding to fix these issues.

2025-02-13 18:34 UTC, maxq519 approved these changes, later dismissed

2025-02-13 18:56 UTC, TINYBOB1 submitted a review, later dismissed
Some well needed and amazing looking upgrades!

2025-02-15 20:46 UTC, maxq519 approved these changes
All looks good

2025-02-16 17:23 UTC, ThatRedMelon approved these changes
Hopefully the final time I approve this, all still looks great! 😆

2025-02-16 17:39 UTC, indy91 approved these changes

2025-02-16 18:45 UTC, merged