Added Plaque meshgroup to landing gear animation
dseagrav/NASSP pull request #1236
Opened 2024-05-24 13:50 UTC by TINYBOB1

The plaque on the landing leg wasn't in the animation for the gear, thus it was floating in the deployed position all the time.  This is now fixed.  (shoutout to ThatRedMelon on the discord for pointing out this oversight)

2024-05-24 18:20 UTC, maxq519 requested changes
The state of the gear animation is being set twice.
Could we get rid of the first instance in each case?
Lines 254 and 259 in [Sat5LMDSC.cpp](https://github.com/orbiternassp/NASSP/pull/1236/files#diff-a87477d6492837668d8d5697ee6c121f10e50d332abc79de1f83fe6a0e818b32)
Lines 421 and 426 in [lm_eds.cpp](https://github.com/orbiternassp/NASSP/pull/1236/files#diff-822aea0b0fce6fcd26bca9d977c2520ccf5e3a71bc24606237a5702d2a4e272a)

2024-05-24 19:02 UTC, TINYBOB1 commented
ill take a look

2024-05-24 19:11 UTC, TINYBOB1 commented
should be fixed, thanks @maxq519

2024-05-26 14:55 UTC, maxq519 approved these changes

2024-05-26 15:10 UTC, merged