Implement GSE cryo dewars, remove cabin heater boilers from cabin fans
dseagrav/NASSP pull request #1305
Opened 2024-10-16 15:14 UTC by rcflyinghokie

2024-10-16 20:24 UTC, rcflyinghokie commented
Only issue is since the old config has the valves open, loading new scenarios will cause cryo pressure drops. IN valves need to be manually closed in the scn unless code can be added to check this.

2024-10-26 08:51 UTC, ThatRedMelon submitted a review, later dismissed
As much as I can tell, the cryo systems remained stable throughout countdown up until liftoff. Comparing scenarios before and after T-2:15, the IN valve closes correctly and systems still remain stable.

2024-10-31 15:28 UTC, ThymoNL commented on Orbitersdk/samples/ProjectApollo/src_csm/satsystems.cpp
> +		//CabinHeater->SetPumpAuto();
If code is no longer needed it should be removed instead of commented out.

2024-10-31 15:28 UTC, ThymoNL commented on Orbitersdk/samples/ProjectApollo/src_csm/satsystems.cpp
> +		//CabinHeater->SetPumpOff();
Idemdito

2024-10-31 15:29 UTC, ThymoNL requested changes
See comments

2024-10-31 17:39 UTC, rcflyinghokie commented
> See comments

Removed!

2024-11-05 14:02 UTC, ThymoNL requested changes
Can you squash 037fda2d7f3d3d8deda6b37d4a26fdf7058eeb8a into f2e939765f1682e775cd6829d18d9fb3ff2358a7 to make your commits atomic? Looks good otherwise.

2024-11-05 14:24 UTC, rcflyinghokie commented
> Can you squash [037fda2](https://github.com/orbiternassp/NASSP/commit/037fda2d7f3d3d8deda6b37d4a26fdf7058eeb8a) into [f2e9397](https://github.com/orbiternassp/NASSP/commit/f2e939765f1682e775cd6829d18d9fb3ff2358a7) to make your commits atomic? Looks good otherwise.

I tried to and instead it merged the main repo I have no idea why

2024-11-05 14:47 UTC, closed without merging