Rework spacecraft attitude controls to not trigger direct coils or hardover by default
dseagrav/NASSP pull request #1310
Opened 2024-10-25 23:34 UTC by CaptainSwag101

As the title says, this overrides Orbiter's default attitude control handling to implement attitude/rotation controller deflection just shy of each vehicle's respective trigger point for direct thruster fire. 

The direct trigger point is 11 degrees deflection out of a maximum 11.5 degrees in the CSM, and 12 degrees deflection out of a maximum 13 degrees in the LM, per each vehicle's AOH Volume 1.

To override this and command full deflection of the attitude controller, simply hold the left or right Alt key while commanding rotation. This allows for much more pleasant control by default when using the keyboard, and prevents accidental direct thruster fire and wasted fuel, which would always occur previously because Orbiter commands 100% thrust with its input handling.

2024-10-26 16:14 UTC, CaptainSwag101 commented
I can't make this change from mobile at the moment, but please temporarily consider this PR unfinished. I want to expand its scope to enable the out-of-detent signal for the LM and potentially CSM, to allow for the on-surface thruster checks without using fuel.

2024-10-26 16:40 UTC, n7275 commented
> I can't make this change from mobile at the moment, but please temporarily consider this PR unfinished. I want to expand its scope to enable the out-of-detent signal for the LM and potentially CSM, to allow for the on-surface thruster checks without using fuel.

I marked it as draft for you.

2024-10-28 03:56 UTC, CaptainSwag101 commented
This PR is now ready for review! I have significantly revised the description above to detail all the changes made. In particular I'd really appreciate some help looking into the minimum value for the CSM rotation hand controller proportional rate transducers. In the LM, proportional rate goes from 1 degree of deflection to 11 degrees. In the CSM it goes from ??? degrees to 10 degrees. The AOH volume 1 makes mention of the rate command signal being routed "through the RC breakout logic" but the schematics it references don't make it clear whether or not the breakout switches, located at 1.5 degrees of deflection, are actually the trigger for proportional rate to begin.

2024-11-07 10:14 UTC, ThymoNL commented
How are we going to communicate this to new and existing users?
I think it's good to make an article on the wiki about this and some sort of announcement on the forum also wouldn't hurt.

2024-11-08 22:50 UTC, CaptainSwag101 commented
I definitely plan on making a forum post about this. My hope, also, is that this change will be mostly not noticed by users if they don't happen to see it mentioned. The default behavior under most circumstances will remain unchanged; only in edge cases such as engine burns will the behavior differ, and even then the behavior ought to be more desirable than it was before. I think the "NASSP keyboard controls" forum post also ought to be updated with this new information.

2025-01-08 17:36 UTC, ThatRedMelon reviewed
Overall the entire PR works with the correct keybinding and expected results. I can't test the vesim or joystick implementation as I don't have one to try, but the numpad controls work perfectly. Seems all good on my end, but I'll save on approving until someone can test with a joystick/vesim, as well as the debug line I left a comment on.

2025-01-08 17:36 UTC, ThatRedMelon commented on Orbitersdk/samples/ProjectApollo/src_csm/scs.cpp
> +		 sprintf(oapiDebugString(),"SCS: RATE CMD r%.3f p%.3f y%.3f ERR r%.3f p%.3f y%.3f",
Should this still be uncommented?

2025-01-08 17:44 UTC, CaptainSwag101 commented on Orbitersdk/samples/ProjectApollo/src_csm/scs.cpp
> +		 sprintf(oapiDebugString(),"SCS: RATE CMD r%.3f p%.3f y%.3f ERR r%.3f p%.3f y%.3f",
No it should not, nice catch!

2025-01-09 20:43 UTC, ThatRedMelon submitted a review, later dismissed

2025-01-10 17:32 UTC, indy91 requested changes
Just the initialization of the rhc_keyboard_deflection variables as the talked about on Discord, then this PR is ready to go!

2025-01-13 17:37 UTC, indy91 approved these changes

2025-01-13 17:37 UTC, merged