Drag Update
dseagrav/NASSP pull request #665
Opened 2021-11-29 16:31 UTC by indy91

2021-12-07 22:28 UTC, ThymoNL requested changes

2021-12-07 22:28 UTC, ThymoNL commented on Orbitersdk/samples/ProjectApollo/src_csm/saturnmesh.cpp
> +	for (i = 0; i < nabsc - 1 && AOA[i + 1] < aoa_T; i++);
It took me a while to understand what you are doing here. While a loop without body is totally valid code, it does increase the cognitive load of the person reading it as it is not obvious that you use i later on.

To make it clear you are using this value how about doing it in the loop body? Something like:
```c
int someVar;
for (int i = 0; i < x ; i++)
    someVar++;
```
The compiler will most likely optimize it away (if you are worried about that) nor will it affect complexity.
Alternatively, I would at the very least comment what you are doing and change i to a descriptive name.

2021-12-07 22:28 UTC, ThymoNL commented on Orbitersdk/samples/ProjectApollo/src_csm/saturnmesh.cpp
> +	for (j = 0; j < nabsc - 1 && AOA[j + 1] < abs(aoa); j++);
Same here

2021-12-07 22:28 UTC, ThymoNL commented on Orbitersdk/samples/ProjectApollo/src_csm/saturnmesh.cpp
> +	for (i = 0; i < nabsc - 1 && AOA[i + 1] < abs(aoa); i++);
Same here

2021-12-07 22:28 UTC, ThymoNL commented on Orbitersdk/samples/ProjectApollo/src_saturn/sat1bmesh.cpp
> +	for (i = 0; i < nabsc - 1 && AOA[i + 1] < aoa; i++);
Same here

2021-12-07 22:28 UTC, ThymoNL commented on Orbitersdk/samples/ProjectApollo/src_saturn/sat5mesh.cpp
> +	for (i = 0; i < nabsc - 1 && AOA[i + 1] < aoa; i++);
Same here

2021-12-07 22:28 UTC, ThymoNL commented on Orbitersdk/samples/ProjectApollo/src_saturn/sivb.cpp
> +	for (i = 0; i < nabsc - 1 && AOA[i + 1] < aoa; i++);
Same here

2021-12-08 19:34 UTC, ThymoNL approved these changes

2021-12-13 16:01 UTC, n7275 approved these changes

2021-12-13 17:17 UTC, merged