Launch window processor
dseagrav/NASSP pull request #773
Opened 2022-04-26 18:01 UTC by indy91

2022-05-01 15:47 UTC, n7275 approved these changes, later dismissed

2022-05-01 21:10 UTC, ThymoNL approved these changes

2022-05-01 21:10 UTC, ThymoNL commented on Orbitersdk/samples/ProjectApollo/src_rtccmfd/ARCore.cpp
> +		if (!stricmp(vessel->GetClassName(), "ProjectApollo\\Saturn1b") ||
This is replicated in quite a lot of places. Probably could be put into some util function.

2022-05-01 21:18 UTC, ThymoNL requested changes
Waiting for documentation

2022-05-03 10:17 UTC, ThymoNL approved these changes

2022-05-03 10:17 UTC, merged