Apollo12 Full MCC and Checklist Support
dseagrav/NASSP pull request #950
Opened 2023-04-14 03:36 UTC by n7275

This pull request/branch contains checklist and MCC updates, mostly for Apollo 12. Other Checklist changes were made while flying Apollo 12.

Checklist and some MCC changes come from --> @rcflyinghokie 
Mcc/RTCC changes come from --> @indy91 
and a few scenario updates from --> @maxq519 

The table below shows the commits that were extracted from my [liquidDensity](https://github.com/n7275/NASSP/tree/liquidDensity) branch into the branch --> Apollo12Ryan merge commits were excluded.

I have tested that all the prelaunch scenarios load and this this builds fine. It just needs a few more pairs of eyes on it. 

<html> 

<body>

Commit ID| Branch|  Notes
-- | -- | --
31395bd45b89d06be88bff3cb4925ee02dc2996e | RRInertialSlew | 
c82168e0439ffd4234093d9e602158f51f6f7038 | RRInertialSlew |  
3085035d8e9021179f45251ac88ce507a227f292 | RRInertialSlew |  
5440d3930183a9299797fd9d8a6fa255b12c5dcc | MERGE |  
daec87803ec70fe0e784a7ad5d6b90c18ab243f0 | Apollo12Ryan   |  
e661d590697245334544c6ceb575adee89ca1b67 |   |  
8f7f1cd414795bec1f467bca0a11cddfebaefe49 |   |  
a3f73b3c8caeb1c0367e1a1199a34c38bed63a1b |   |  
eae08cfa73f1c1813c8432c40fa088e7ee31ea78 |   |  
79a6df59bba40e05f3eda75ae5873f494ccd7833 |   |  
99a7acb2fbf20d015cb2dc0a5c32067b21853e3c |   |  
327978c570dc8f8d4845f75b5c2018a4df706b58 |   |  
a46f99278b5600b2ab2a3dbe961ebd064fcf82d5 |   |  
d69548d6d134ffbee9294130dd9d8715c94d308b |   |  
5730ede9d157838fa66312cc8368791a9b4bb421 |   |  
4a3bb179f6e4c436ddeef813aa613040d5727af0 |   |  
68636597e4cff2186aed4d42d8d0620d149666a3 |   |  
408f095767d1e92f9945b547384a20d4bf3f2a3e |   |  
bb2cc994061118ddcceaffffa57a8617038fbf75 | FC Nitrogen |  
bf0313e137b8deb4ed1bf870fb373c596ecf22e0 | FC Nitrogen |  
11e819415b3dee88764e98f368a26e73d88eb4d8 |   |  
6700d9b94ab99a2374a786ea9c89b7b23d800619 |   |  
9974dda68cf3b570af587873629715e11a4ddbac |   |  
73aaa6c55d2d0a3d2920eca68fdab8b761cd6057 |   |  
d58e80061436685a12addb2ca7ca27e059f8dfa1 |   |  
b23e1913c03683e1907c767ea9b6b8c0dd1096b6 |   |  
f852cee5a49f86033391a4ec4d25d2347e85d7d4 |   |  
59c7be79c0b47e5bc2b5a5087f7bdc93fadf64e7 |   |  
f4a1d5b918085e3133e41374b3bd28abc540e850 |   |  
2b8b558c199e3604128e8d015de5baa7c6563b22 |   |  
d0bfe32e86b4bf4570185047911f14ed7a18d17e |   |  
328a1e1dbd5c7ae4ea4ae79f708ba4fbe0736119 | FC Nitrogen |  
feb34a98fcf562d600ecc0be0bc56f78a6b024b0 | Apollo12Ryan |  
9dc421fa742de38c49c2ec162750782bace1e30d | MERGE |  
7137499a5c503ed6a65bda42e69e42031c7ecff3 | MERGE |  
4b06b754ab9413fa6d6f6be30567f1fe4540d515 | FC Nitrogen |  
983cc0fbb7183732509c1d9b2c130a088910207a |   |  
213716d3b634b0772edfc8df79d614cd1afbbe42 | MERGE |  
99b207244b7e90fd4033568b1ce5f0774369af9f | LiquidDensity2 |  
035316aec83aabfe091baa4ade8da4e9b399307f | Apollo12Ryan |  
fdc65d0d9149585ffae5ba4b9d37e210d32e0449 | LiquidDensity2 |  
f7e06bc85725b821d2ee326310b61aa0a56c3ec1 | MERGE |  
64fb24d86d9dd634dcb3af29b6d76c4306b555ff | Apollo12Ryan |  
305fb86876b16d049c62764afac274af26192382 | LiquidDensity2 |  
414b0ee8c64db3af42bfebc1ae9e4fada2f810a0 | LiquidDensity2 |  
586f8a4ff494b7ecb4457fe0a01175342a11fcaf | Apollo12Ryan |  
ce30dff3c95c149b2c1a939942c064d95a760a9f | MERGE |  
b19f461ffce29f4ff75704103ce0377c02392008 | Apollo12Ryan |  
793f6174d7b4e4c2f065bdf03634cb9ca8835358 | Apollo12Ryan |  
04254d5c84c942e983c87fa4d9bd36771c75a0ce | Apollo12Ryan |  
5ca2a70fce6fb79d686ea63c3600d83b6b157f68 | LiquidDensity2 |  
542a258652a112f15bf9f3ed69b6fecd79ee32af | Apollo12Ryan |  
83eb1cd1668f0a5403b55ecaca96b6a509a52cce | MERGE |  
63b18d5715ad909e06b3b9a8ca98a1aef9f07d05 | Apollo12Ryan |  
4495054e3d4b136c420bdbc60dc3951d13c44a69 | MERGE |  
8bebb40294898203c7257cbd922e15776e7db629 | Apollo12Ryan |  
4d77ccf1676c061524ffaa4549bbf0f77c57d99c | Apollo12Ryan |  
6b8c2402d4ac968b4b058cc4b3ac502a32e25bce | Apollo12Ryan |  
ba6f0f7a7557114c51ad9472fdf55597502b2e66 | Apollo12Ryan |  
63f9f244b4f13f473eef0ef3cebb990079d64578 | Apollo12Ryan |  
924338dca0de96d78f96e3f2f0969fac9c432ac0 | MERGE |  
0f2c2a7a0a8828269a1aad3a0295878a42559571 | Apollo12Ryan |  
3946d8df9dbb519b8ea09b126727b54bc71cee0d | Apollo12Ryan |  
c103c799a9b4c6acc48a4e585806149e37610087 | Apollo12Ryan |  
13dabd6468a6bb878e95dbcb53a5edeef2043b36 | Apollo12Ryan |  
f302529923308eb78eb6b97210713ee0ad23dab4 | Apollo12Ryan |  
f88052cdd49de1e2766bdabfd7d06bea5ff74760 | MERGE |  
0f938f7b1b7174c3ff7ebd0f1c6777bfcf4007d5 | Apollo12Ryan |  
0c6eb0b6661d0c2c68901e61494d29bd59794c91 | Apollo12Ryan |  
116c08d43518672f3d49ee21ee1d13e9a617bbb3 | Apollo12Ryan |  
cad0553b2b33a57beaa8128c5d7a44fce94ecb93 | Apollo12Ryan |  
a3fb9e7d1ec0c5ccdbf763703d2e3da145887c95 | Apollo12Ryan |  
e096274cd4053381790c07abea841465469e257f | Apollo12Ryan |  
f25f5c5b38d07d81779cd89af4367f6bc67544f4 | MERGE |  
486ef30b25a5072f1f1a13097571a13eac9eddf7 | Apollo12Ryan |  
99f7b65be0e5eefcc51a3b6c070c11aa6cb7a6d6 | Apollo12Ryan | *
140a4509df504c9c9994b6bfaae0354c80bfdf90 | Apollo12Ryan |  
34a03b07cfded27b25e965677a9b3d60955c7d21 | Apollo12Ryan |  
b7d4243de7a0a8e9169414ffa475c348ead46fb6 | MERGE |  
9213d68de3145f3a8806c6a7704ec6decc345a91 | Apollo12Ryan |  
6a7c6a809f9f13a24bc15c26ef3b3db78bd137c1 | Apollo12Ryan |  
b92a872e9c479b60b59d35bc558071352545172b | MERGE |  
2553f6f4aab8491c5df1fef4b47e18b0f4c1b0ae | Apollo12Ryan |  
5051ff7b634be2c21f5261acccef721b17d7dd1c | Apollo12Ryan |  
06abb77112c1b52262efbd4997abd7d1719439ff | MERGE |  
115f85e06a37fbfbd840d05cd625693a917bf4f1 | Apollo12Ryan |  
adec0039b9cc965ee01fef2dd83472ebea4c440d | Apollo12Ryan |  
e71c24596df453d400d21b9045e394568fdc2b4e | Apollo12Ryan |  
4670efa21446a0774b45bafbde6182e1b9d2bf95 | MERGE |  
0c8b6f903bc2e0f6246a8a068456d97450e64316 | Apollo12Ryan |  
8d2e1b4065bd5490c18047d2b93b2ce7126ca3c2 | Apollo12Ryan |  
de9b3337550d5feccb64f91dbf58e624a46097ea | MERGE |  
f9280622790caf44581e3e9d03fd8191072a7297 | Apollo12Ryan |  
283756b6f5ccd4e72ef851b54bb6f3a91ce8d539 | Apollo12Ryan |  
7f167b9cfea4cef7a3eb2cb3c0986a2edf3a7f02 | MERGE |  
8271526a050f094d20543f687626410935810965 | Apollo12Ryan |  
69c33d646d45cf6cb715fa8cdeee5103e11fdf9e | Apollo12Ryan |  
9259fd793a86b2cc4db41f5a3b699af36e0d67ea | MERGE |  
1f3aa1d650ae95d17252d68554f4f738015efc7d | MERGE |  
319dfb22087fdb6bc97b64f97a2b8b493643250e | Apollo12Ryan |  
7661875a51b2fe36270c9d0a8856af6d8dc252af | Apollo12Ryan |  
59d4b43f90bda191ef9985949227a1c00f7f23a3 | Apollo12Ryan |  
a9d9a5527e2fa02b1a7641b754f02364fafaaf68 | MERGE |  
4918f678d9542871f1b36694cfa7c193c5e68375 | rewrite_radiative |  
8f76483abefcb61c23fb7621dde1509a211c441a | Apollo12Ryan |  
653460884ea6ffebc345b0cf4a44f1c1dbcd1e40 | rewrite_radiative |  
c046e5280675b9705a4fd00129e48bd409275cf1 | rewrite_radiative |  
dcc6c7e7b94bc8efbbbd851815913549795ffb23 | rewrite_radiative |  
38d4bf6f7c3afaf624ecc3f001f55e884718f3d5 | MERGE |  
f85f42ff245be6f2ab3023f73019f38f9ebdb8c9 | Apollo12Ryan |  
07de896e841ccf965e6fe8d9f78e15a49ddb4079 | Apollo12Ryan |  
c94d09bfe51b54aa370ba007809ea811644d23d0 | MERGE |  
29398b1ed8077f1c35aae420eb074aaed412bde1 | Apollo12Ryan |  
a14b3e1048c720d4e14d1043fbe1ca2369135997 | MERGE |  
2c003209e5ce86ba8b8b54f842aa11a9feac6ebe | Apollo12Ryan |  
472d665526411f9eba6715865ccb609ae5a4fd7d | Apollo12Ryan |  
dfc84a5245d9c117a215aba4b51a199eca8d7734 | MERGE |  
cc38451a20d32f323583be7fa8b9c11c689c9979 | Apollo12Ryan |  
19917cb1822b07ceca0d2fac53bf9f18f98b5f62 | MERGE |  
1a988005568177d046b329acb6f8ae439967fad1 | Apollo12Ryan |  
d263affa6339771716c6eef9f9bcf66a32231908 | Apollo12Ryan |  
5f5ead1d326e75b8ed7d72d7104cda00a9e497cf | MERGE |  
aec653668cbc7d82bb543d2b9269e949f7dac6c7 | Apollo12Ryan |  
eb4113b45f6b9df487fe191214855245ab25d404 | Apollo12Ryan |  
061571c644a81d7a207f1a17e35990f81558eb9c | MERGE |  
394a3093c4e4820bf5c9c89f4f7fae68fa817bd0 | Apollo12Ryan |  
0bc45bf981e9aee0102b98935f91e6b8b7d69d18 | MERGE |  
c5506f9bb5db9de46b4772cb7146b07b91c7ef78 | Apollo12Ryan |  
77084b0500c7389358f4c6f2f7f3edee3711dba1 | Apollo12Ryan |  
74826aeaf822aa463919ade9e8 [...]

2023-04-15 08:46 UTC, indy91 commented
This branch still has an Apollo 12 launch scenario in the WIP folder, while also having added the new one in the main NASSP folder.

2023-04-15 16:58 UTC, indy91 submitted a review, later dismissed

2023-04-16 08:19 UTC, indy91 submitted a review, later dismissed

2023-04-17 15:27 UTC, rcflyinghokie requested changes
Checklist files are not ready to merge

2023-05-12 16:20 UTC, n7275 commented
#975 supercedes this PR

2023-05-12 16:20 UTC, closed without merging